// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxdxefvmkepkopfvvmql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4ZHhlZnZta2Vwa29wZnZ2bXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzg1MjIsImV4cCI6MjA3Mjg1NDUyMn0.zbiplk5VxFBv6_5OdCkIcgt3UzN-yZ9ucBzZ2TxLMkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});